### ISSUE TITLE
问问咋编译的

### ISSUE THREAD

**Issue by a952135763** [bb107/MemoryModulePP#1]
你添加的 comment 命令
`#ifdef _WIN64
#pragma comment(linker,"/export:LdrUnloadDllMemoryAndExitThread")
#pragma comment(linker,"/export:FreeLibraryMemoryAndExitThread=LdrUnloadDllMemoryAndExitThread")
#else
#pragma comment(linker,"/export:LdrUnloadDllMemoryAndExitThread=_NtUnloadDllMemoryAndExitThread@8")
#pragma comment(linker,"/export:FreeLibraryMemoryAndExitThread=_NtUnloadDllMemoryAndExitThread@8")
#endif`
编译的时候老这里报错

**Comment by bb107** [comment]
问题已修复
