### ISSUE TITLE
Win7 SP1 64 位下 处理C++ 异常会导致奔溃

### ISSUE THREAD

**Issue by 9844201** [bb107/MemoryModulePP#14]
void Test()
{
	MessageBox(NULL, TEXT("memory module load successfuly."), TEXT("info"), MB_ICONINFORMATION);

	PCHAR	p = NULL;
	__try{
		*p = '0';
	}
	__except (EXCEPTION_EXECUTE_HANDLER)
	{
		MessageBox(NULL, TEXT("exception 1"), TEXT("info"), MB_ICONINFORMATION);
	}

}
这个Test()异常能正常处理

void Test2()
{
	std::string str("foo");
	try {
		str.at(10); // access element, may throw std::out_of_range   
	}
	catch (const std::out_of_range& e) {
		// what() is inherited from std::exception and contains an explanatory message       
		MessageBox(NULL, TEXT("exception 2"), TEXT("info"), MB_ICONINFORMATION);
	}
}
Win7 SP1 64 位下 内存加载64位DLL 处理C++ 异常Test2()会导致奔溃 跟踪是在 RtlpWaitOnCriticalSection 这个函数

[TargetDll_x64.zip](https://github.com/bb107/MemoryModulePP/files/9661307/TargetDll_x64.zip)

**Comment by bb107** [comment]
你好，我在虚拟机环境里用样本和自己写的程序测试过，没有复现出上述问题。

**Comment by 9844201** [comment]
我测试 是WIN10 64 WIN11 64 都没问题 
我用的是vs2017 编译的 唯独就是WIN7 64有问题 Win7 64  运行32的DLL 也没问题，
