### ISSUE TITLE
程序静态链接该库后，程序内的LoadLibraryW调用会引发崩溃

### ISSUE THREAD

**Issue by DsoTsin** [bb107/MemoryModulePP#22]
Win11 32位程序下：
1. 静态链接MemoryModulePP
2. 启动程序
3. 程序中调用 LoadLibraryExW 加载 dll （CoreFoundation.dll）
4. 程序崩溃

> 注释掉 `const NTSTATUS Initializer = Initialize();` 后能正常调用Win32的LoadLibrary

**Comment by DsoTsin** [comment]
调用Win32的`LoadLibrary`后，调试器提示
```
Exception has occurred: W32/0xC0000005
Unhandled exception at 0x764BFF26 (shell32.dll) in apple_developer-58c03d957f278b99.exe: 0xC0000005: Access violation reading location 0x00000004.
```

**Comment by bb107** [comment]
你好，我在Win11 Wow64环境和Win10 x86环境下没有复现这个问题，请问这个问题发生在调用LoadLibrary过程中还是调用CoreFoundation库内函数时发生的？
![Snipaste_2023-03-04_08-14-44](https://user-images.githubusercontent.com/20726245/222858664-cd2d9f34-f259-463a-b61a-34bfac369dc4.png)
![Snipaste_2023-03-04_08-15-27](https://user-images.githubusercontent.com/20726245/222858680-a2275296-2f1b-4263-adc8-c7fb7762df65.png)

**Comment by DsoTsin** [comment]
可能是我用的detours库（不是这个项目里带的）有问题
