### ISSUE TITLE
32位模式内存加载CoreFoundation失败

### ISSUE THREAD

**Issue by DsoTsin** [bb107/MemoryModulePP#24]
### 崩溃位置
![](https://github.com/Tsinworks/MemoryModulePP/blob/ic/test/screenshot/crash.png?raw=true)

### 加载CoreFoundation
![](https://github.com/Tsinworks/MemoryModulePP/blob/ic/test/screenshot/crash2.png?raw=true)

### 项目链接
https://github.com/Tsinworks/MemoryModulePP/tree/ic

测试数据 https://github.com/Tsinworks/MemoryModulePP/tree/ic/test/data

**Comment by bb107** [comment]
你好，这个问题是32位RtlUserThreadStart传参方式不同导致的，最新的提交修复了这个问题，并且在我的系统上运行良好。

![Snipaste_2023-03-10_11-25-07](https://user-images.githubusercontent.com/20726245/224215576-90ca3376-ede8-49b7-9798-87489e15be1e.png)
