### ISSUE TITLE
帧不在模块中

### ISSUE THREAD

**Issue by woowloop** [bb107/MemoryModulePP#30]
一个用ue打包成的c++ dll(a.dll) 直接加载在执行到LdrpCallInitializers时会报”帧不在模块中“。经测试不是tls处理的问题----注释掉处理tls的代码采用直接获取LdrpHandleTlsData指针调用报同样错误。
另一个问题如下
a.dll是依赖b.dll的 （b.dll是可以内存加载成功）
首先修改MemoryModoule文件240行 VirtualAlloc(LPVOID(old_header->OptionalHeader.ImageBase),......)修改为 VirtualAlloc(NULL,......)
内存加载b.dll
内存加载a.dll 在进行到MemoryResolveImportTable函数的时候GetProcAddress获取b.dll的函数有很高概率返回空 错误码126

**Comment by bb107** [comment]
你好，126错误是没有找到模块，失败的原因是LoadLibrary返回了空。你在加载b.dll时有没有为其指定名称？就像下面这样：
``` C++
    LoadLibraryMemoryExW(
        buffer,
        0,
        L"b.dll",
        L"\\000\\b.dll",
        0
    );
```

**Comment by woowloop** [comment]
只指定了名字
HMODULE hm = LoadLibraryMemoryExW(buffer, 0, L"b.dll", nullptr, 0);
LoadLibrary 和 GetModuleHandle是正确返回句柄的
刚刚测试同时指定路径也是同样的问题

**Comment by woowloop** [comment]
LoadLibrary 如果返回空GetProcAddress的错误码应该是127

**Comment by bb107** [comment]
我这边测试的，无论hModule是否为空都返回127

**Comment by bb107** [comment]
有没有打断点跟踪一下，看看是获取哪个函数失败了

**Comment by woowloop** [comment]
只要是b.dll中函数都是失败的

**Comment by woowloop** [comment]
如果不加载a.dll 直接内存加载b.dll后GetProcAddress获取的函数都是成功的 错误是在加载a.dll后再去获取b.dll的函数都是空了

**Comment by bb107** [comment]
有用其他加载程序试过吗？比如BlackBone？

**Comment by woowloop** [comment]
BlackBone 在加载b.dll时候报Microsoft C++ 异常: std::bad_optional_access 在直接加载a.dll的时候报帧不在模块中
留个邮箱这几个测试dll可以发给你

**Comment by bb107** [comment]
microboring107@gmail.com

**Comment by bb107** [comment]
![Snipaste_2023-03-30_12-59-23](https://user-images.githubusercontent.com/20726245/228734010-4bfcf319-8dbb-4b5d-a909-00351189004e.png)

**Comment by woowloop** [comment]
好了 你再试试
