### ISSUE TITLE
链接器选项 /DYNAMICBASE:NO 引发的崩溃

### ISSUE THREAD

**Issue by ouyangyiluo** [bb107/MemoryModulePP#31]
如果内存加载使用了链接器选项 /DYNAMICBASE:NO 编译后的DLL,会引发崩溃，可以在示例a.dll上复现。
经过调查后是以下原因导致的：
如果[此行](https://github.com/bb107/MemoryModulePP/blob/c958100b8b8898052c2915a7cf8a2accfbc4f374/MemoryModule/MemoryModule.cpp#L275)条件未成立。base变量此时依旧为nullptr，status变量为 STATUS_SUCCESS，[条件](https://github.com/bb107/MemoryModulePP/blob/c958100b8b8898052c2915a7cf8a2accfbc4f374/MemoryModule/MemoryModule.cpp#L286)不足以返回，后续代码对base 变量操作时引发崩溃。

根据我了解到的[信息](https://stackoverflow.com/a/39216123)，屏蔽[此行](https://github.com/bb107/MemoryModulePP/blob/c958100b8b8898052c2915a7cf8a2accfbc4f374/MemoryModule/MemoryModule.cpp#L275)条件判断，直接分配，DLL是可以正常加载的。

**Comment by bb107** [comment]
感谢反馈，问题已修复
