### ISSUE TITLE
Go编译的DLL无法加载

### ISSUE THREAD

**Issue by ouyangyiluo** [bb107/MemoryModulePP#32]
Go编译出来的DLL无法使用MemoryModulePP加载，如果我使用LoadLibrary()是可以正常加载DLL的。
在使用MemoryModulePP加载DLL的时候，始终无法通过[校验和验证](https://github.com/bb107/MemoryModulePP/blob/5fb7f591d271fda24f11753ca2c555c6d0c8d5f6/MemoryModule/Utils.cpp#L339)，最终加载失败。

我做了简单的尝试，直接在[此处](https://github.com/bb107/MemoryModulePP/blob/5fb7f591d271fda24f11753ca2c555c6d0c8d5f6/MemoryModule/Utils.cpp#LL337C16-L337C16)跳过了校验和验证，是可以使用MemoryModulePP加载DLL的并调用函数。
是否可以考虑增加跳过校验和验证的选项。

附加文件：
[godll.zip](https://github.com/bb107/MemoryModulePP/files/11384196/godll.zip)

**Comment by bb107** [comment]
你好，mydll.dll的校验和确实不正确。如果需要跳过校验，只需要提供```LOAD_FLAGS_PASS_IMAGE_CHECK```标识给```LdrLoadDllMemoryExW```函数即可。
