### ISSUE TITLE
加载_运行_释放_再加载_再运行，有很大几率报错：帧不在模块中

### ISSUE THREAD

**Issue by hnzhw** [bb107/MemoryModulePP#33]
代码结构如下：
while(true)
{
    ...
    LdrLoadDllMemoryExW(...);
    func = (FUNCW)GetProcAddress(...);
    func();
    LdrUnloadDllMemory(...);
}
调试跟踪，首次运行均正常，循环后再次运行func()有很大几率报错“帧不在模块中”，但有较低几率执行正常

**Comment by bb107** [comment]
你好，有试过使用```LdrpTls```模式编译吗？我使用a.dll测试没有复现出来这个问题。提供```func```函数的执行过程和详细的异常信息可以更快地定位问题。

**Comment by bb107** [comment]
使用```LdrpTls```需要在```MmpLdrpTls.cpp```第28行和116行补充特征码。

**Comment by hnzhw** [comment]
OK，谢谢
