### ISSUE TITLE
在调用枚举摄像头设备的dll时出现奇怪的崩溃

### ISSUE THREAD

**Issue by woowloop** [bb107/MemoryModulePP#40]
崩溃堆栈如下，看着像是延迟加载dll导致的。
![image](https://github.com/bb107/MemoryModulePP/assets/18320534/6facf97b-0555-4674-876f-a130b4d0443a)
刚开机得时候没有问题，过一段时间后只要调用就崩溃。

奇怪得是把枚举摄像头得代码单独拎出来测试又没有问题。在把MmpGlobalDataPtr改成(PMMP_GLOBAL_DATA)RtlAllocateHeap(RtlProcessHeap(), HEAP_ZERO_MEMORY, 0x2000);的方式后会较高概率出现崩溃。
出现崩溃时会发现有两次dll_thread_attach如下
DLL_PROCESS_ATTACH
DLL_THREAD_ATTACH
DLL_THREAD_ATTACH
001
crash
正常情况是
DLL_PROCESS_ATTACH
DLL_THREAD_ATTACH
001
002
....
DLL_THREAD_ATTACH
DLL_THREAD_DETACH
DLL_PROCESS_DETACH

采用系统LoadLibrary或通过特征码获取LdrpHandleTlsData得方式都没有问题。
枚举摄像头的代码如下

#include <atlbase.h>
#include <dshow.h>
#pragma comment(lib, "strmiids.lib")

#define SAFE_RELEASECOM( x ) \
if ( NULL != (x) ) \
{ \
  (x)->Release(); \
  (x) = NULL; \
}
BOOL RunThread()
{
    ICreateDevEnum* pCreateDevEnum = nullptr;
    ICaptureGraphBuilder2* pBuilder = nullptr;
    IBaseFilter* pVCap = nullptr;
    IAMStreamConfig* pVSC = nullptr;
    if (CoInitialize(nullptr) != S_OK)
    {
        return FALSE;
    }
    HRESULT hr = CoCreateInstance((REFCLSID)CLSID_CaptureGraphBuilder2,
        nullptr, CLSCTX_INPROC, (REFIID)IID_ICaptureGraphBuilder2,
        reinterpret_cast<void**>(&pBuilder));
    hr = CoCreateInstance(CLSID_SystemDeviceEnum, nullptr, CLSCTX_INPROC_SERVER, IID_ICreateDevEnum, reinterpret_cast<void**>(&pCreateDevEnum));
    if (hr != NOERROR)
    {
        return FALSE;
    }
    IEnumMoniker* pEm = nullptr;
    hr = pCreateDevEnum->CreateClassEnumerator(CLSID_VideoInputDeviceCategory, &pEm, 0);
    if (hr != NOERROR)
    {
        return FALSE;
    }
    pEm->Reset();
    ULONG cFetched = 0;

    IMoniker* pMoniker = nullptr;
    int index = -1;
    while (hr = pEm->Next(1, &pMoniker, &cFetched), hr == S_OK)
    {
        index++;
        IPropertyBag* pBag;
        hr = pMoniker->BindToStorage(nullptr, nullptr, IID_IPropertyBag, reinterpret_cast<void**>(&pBag));
        if (hr != S_OK)
        {
            continue;
        }
        VARIANT var;
        VariantInit(&var);
        var.vt = VT_BSTR;
        hr = pBag->Read(L"FriendlyName", &var, nullptr);
        if (hr == NOERROR)
        {
		VariantClear(&var);
        }
        SAFE_RELEASECOM(pBag);
        printf("001\n");
        hr = pMoniker->BindToObject(nullptr, nullptr, IID_IBaseFilter, reinterpret_cast<void**>(&pVCap));
        if (hr != S_OK)
        {
            continue;
        }
        printf("002\n");
        hr = pBuilder->FindInterface(&PIN_CATEGORY_CAPTURE, &MEDIATYPE_Video,
            pVCap, IID_IAMStreamConfig, reinterpret_cast<void**>(&pVSC));
        if (hr != S_OK)
        {
            hr = pBuilder->FindInterface(&PIN_CATEGORY_PREVIEW, &MEDIATYPE_Video,
                pVCap, IID_IAMStreamConfig, reinterpret_cast<void**>(&pVSC));
        }
        if (hr != S_OK)
        {
            continue;
        }
        printf("003\n");
        int iCount = 0, iSize = 0;
        hr = pVSC->GetNumberOfCapabilities(&iCount, &iSize);
        if (hr == S_OK && iSize == sizeof(VIDEO_STREAM_CONFIG_CAPS))
        {
            for (int iFormat = 0; iFormat < iCount; iFormat++)
            {
                VIDEO_STREAM_CONFIG_CAPS scc;
                AM_MEDIA_TYPE* pmtConfig = nullptr;
                hr = pVSC->GetStreamCaps(iFormat, &pmtConfig, reinterpret_cast<BYTE*>(&scc));
                if (hr != S_OK)
                {
                    continue;
                }
                if (HEADER(pmtConfig->pbFormat)->biWidth != 0 && HEADER(pmtConfig->pbFormat)->biHeight != 0)
                {
                    printf("OK\n");
                }
            }
        }
    }
    return TRUE;
}

extern "C" __declspec(dllexport)
BOOL __test2__()
{
    std::thread* pThread = new std::thread(RunThread);
    pThread->join();
    delete pThread;
    return FALSE;
}

**Comment by bb107** [comment]
你好，我用以下代码没有复现
``` C++
int main() {
    
    DisplayStatus();

    HMODULE hm;
    PVOID buffer = ReadDllFile2("a.dll");
    NTSTATUS status = LdrLoadDllMemoryExW(&hm, nullptr, 0, buffer, 0, nullptr, nullptr);
    if (NT_SUCCESS(status)) {
        auto test2 = GetProcAddress(hm, "test2");

        while (TRUE) {
            test2();
            Sleep(5000);
        }
    }

    return 0;
}
```

**Comment by woowloop** [comment]
a.dll 中的RunThread要在线程中开启如#40的案例 然后我的MmpGlobalDataPtr是这么分配的

上面的注释掉
 status = STATUS_SUCCESS;

MmpGlobalDataPtr = (PMMP_GLOBAL_DATA)RtlAllocateHeap(RtlProcessHeap(),
HEAP_ZERO_MEMORY, 0x2000);

刚刚测试了下还是崩。。。

或者你把你的测试程序发给我 如果还是崩溃我可以开启vs的远程调试让你连接(有公网ip)


Boring ***@***.***> 於 2024年1月4日週四 下午2:19寫道：

**Comment by bb107** [comment]
测试程序在我这里运行正常。https://drive.google.com/file/d/1po5M03lWKu6XyYHtFxHmC17tWI5XqJKw/view

**Comment by woowloop** [comment]
Test.rar
<https://drive.google.com/file/d/1RgfJhR1P4zzArrkHJkoUDKREYecNXzx4/view?usp=drive_web>
是你的a.dll和我的不一样
没有在vs编辑器中运行会报一个 （之前一直都是在vs中跑。。。。。）
Assertion failed: p->TlspMmpBlock ==
NtCurrentTeb()->ThreadLocalStoragePointer, file
C:\Users\UserX\Desktop\Test\src\MemoryModule\MmpTls.cpp, line 116
直接注释掉后直接运行会闪退
我把你的工程修改了一下 你现在测测
https://drive.google.com/file/d/1RgfJhR1P4zzArrkHJkoUDKREYecNXzx4/view

Boring ***@***.***> 於 2024年1月4日週四 下午5:35寫道：

**Comment by woowloop** [comment]
另外 如果你要测试直接LoadLibrary加载 需要注释掉Initialize.cpp的初始化代码
#else
//const NTSTATUS Initializer = Initialize();
#endif

None Ghost ***@***.***> 於 2024年1月4日週四 下午6:58寫道：

**Comment by bb107** [comment]
这个链接打不开
https://drive.google.com/file/d/1RgfJhR1P4zzArrkHJkoUDKREYecNXzx4/view

**Comment by woowloop** [comment]
https://drive.google.com/file/d/1RgfJhR1P4zzArrkHJkoUDKREYecNXzx4/view?usp=sharing

**Comment by woowloop** [comment]
https://drive.google.com/file/d/1O-_Kpx0u4LOlyYdVUUCvUW_1nmJjdw_L/view?usp=sharing

**Comment by bb107** [comment]
a.dll引用了MemoryModulePP，test.exe也引用了它，这时如果使用```RtlAllocateHeap```来分配MmpGlobalDataPtr会引起重复初始化，从而引起断言失败。
![Snipaste_2024-01-05_11-04-55](https://github.com/bb107/MemoryModulePP/assets/20726245/459a051c-b877-4601-908a-902a6a9e4f65)

**Comment by woowloop** [comment]
那就麻烦了 不过我确认我的dll是没有引用MemoryModulePP的 崩溃堆栈都是一样 你可以在a.dll中去掉MemoryModulePP的引用，注释掉test_user32。 然后试试正常加载LoadLibrary(L"a.dll") 并调用大概率也会崩溃。。。

**Comment by bb107** [comment]
试试把 a.dll 从解决方案中排除，然后重新添加进来，重新生成

**Comment by woowloop** [comment]
还是崩 不是每次都崩溃
https://drive.google.com/file/d/18PmrTOgXBxfDIvLSkle8ouWYsmc9-2Qj/view?usp=sharing

**Comment by bb107** [comment]
有没有把测试程序放到虚拟机里试一下？我在几个系统里测试都没复现出来。

**Comment by woowloop** [comment]
虚拟机win10 21H2 测试崩溃 win11没有问题 
笔记本win10 22h2测试3台都崩溃（开启摄像头）
台式机两台 win10 22H2 一台有外置摄像头的崩溃 一台没有的没有问题

**Comment by bb107** [comment]
试一下最新的代码

**Comment by woowloop** [comment]
现在调用没有啥问题了 不过运行一段时间有个空报错
![image](https://github.com/bb107/MemoryModulePP/assets/18320534/de8136d6-958b-4c23-882c-0a3c51649446)

**Comment by bb107** [comment]
试过最新的代码吗？

**Comment by woowloop** [comment]
遇到一次崩溃 但后面又测不出来了 先这样吧
