### ISSUE TITLE
无论加载任何dll，一旦执行这个VirtualAccessCheck就会报错 STATUS_ACCESS_VIOLATION，注释掉之后工作正常

### ISSUE THREAD

**Issue by BaiFeng666** [bb107/MemoryModulePP#46]
无论我加载任何dll，一旦执行这个VirtualAccessCheck就会报错 STATUS_ACCESS_VIOLATION

![image](https://github.com/bb107/MemoryModulePP/assets/69395668/8d96391f-c3b4-4c7d-a137-1dc651baa4a3)

于是我尝试注释掉，无论如何返回True

![image](https://github.com/bb107/MemoryModulePP/assets/69395668/47cca8a7-5707-44d5-a66a-531d3fd8c240)

这样做了之后一切工作正常

我不太清楚这个问题发生的原因 希望能修复吧

**Comment by bb107** [comment]
你好，查看一下报错时的调用堆栈，看看是哪个位置产生的异常。

**Comment by bb107** [comment]
我推测你应该是将内存映射文件指针或者具有```PAGE_EXECUTE```保护的内存地址作为DLL参数传递给了```LdrLoadDllMemoryExW```函数。试一下我最新的提交。

**Comment by BaiFeng666** [comment]
> 我推测你应该是将内存映射文件指针或者具有`PAGE_EXECUTE`保护的内存地址作为DLL参数传递给了`LdrLoadDllMemoryExW`函数。试一下我最新的提交。

好的谢谢  我等会尝试一下
